tasks:
  - init: curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64 && chmod +x ./kind && sudo mv ./kind /usr/local/bin
    command: make create-kind-cluster
  - before: GO111MODULE=off go get -u github.com/mgechev/revive; go install honnef.co/go/tools/cmd/staticcheck@latest; go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1; go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
    init: make protoc bin/goreleaser lint build unit-test
  - command: bash ./dev/run-kind-registry.sh && make local-images
  - before: docker-compose up -d
    command: make e2e-test

vscode:
  extensions:
    - golang.go