tasks:
  - init: curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64 && chmod +x ./kind && mv ./kind /usr/local/bin
    command: make create-kind-cluster
  - init: GO111MODULE=off go get -u github.com/mgechev/revive
  - init: go install honnef.co/go/tools/cmd/staticcheck@latest
  - init: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
  - init: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
  - init: make protoc bin/goreleaser
  - init: make build
  - init: make lint
  - init: make unit-test
  - init: make e2e-test
  - command: bash ./dev/run-kind-registry.sh
  - command: make push-local-images

vscode:
  extensions:
    - golang.go