version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: tarian
      POSTGRES_DB: tarian
    shm_size: '256mb'
    ports:
      - 5432:5432
  phppgadmin:
    depends_on:
    - db
    image: bitnami/phppgadmin
    ports:
      - 8090:8080
    environment:
    - DATABASE_HOST=db
    - DATABASE_SSL_MODE=disable
  dgraph-zero:
    image: dgraph/dgraph:latest
    volumes:
      - /tmp/tarian-dev/dgraph/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=dgraph-zero:5080
  dgraph-alpha:
    image: dgraph/dgraph:latest
    volumes:
      - /tmp/tarian-dev/dgraph/data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=dgraph-alpha:7080 --zero=dgraph-zero:5080 --security whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,127.0.0.1

