apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-rotator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-rotator-role
subjects:
- kind: ServiceAccount
  name: tarian-controller-manager
  namespace: system
