# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-agent-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
