apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: 50052
    name: grpc
  selector:
    app: {{ .Release.Name }}
