{{- $name := printf "%s-%s" .Release.Name "cluster-agent" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}