apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: tarian-cluster-agent
        image: "{{ .Values.clusterAgent.image.name }}:{{ .Values.clusterAgent.image.tag | default .Chart.AppVersion }}"
        args:
        - "--log-encoding={{ .Values.clusterAgent.log.encoding }}"
        - "--log-level={{ .Values.clusterAgent.log.level }}"
        - run
        - "--server-address={{ .Values.clusterAgent.serverAddress}}"
{{- if .Values.clusterAgent.falco.grpcServerHostname }}
        - "--falco-grpc-server-hostname={{ .Values.clusterAgent.falco.grpcServerHostname }}"
{{- end }}
{{- if .Values.clusterAgent.falco.grpcServerPort }}
        - "--falco-grpc-server-port={{ .Values.clusterAgent.falco.grpcServerPort }}"
{{- end }}
{{- if .Values.clusterAgent.falco.clientTlsSecretName }}
        - "--falco-grpc-client-cert-file=/etc/tarian/certs/falco-integration/tls.crt"
        - "--falco-grpc-client-key-file=/etc/tarian/certs/falco-integration/tls.key"
        - "--falco-grpc-client-ca-file=/etc/tarian/certs/falco-integration/ca.crt"
{{- end }}
{{- if .Values.clusterAgent.enableAddConstraint }}
        - --enable-add-constraint
{{- end }}
        ports:
        - containerPort: 50052
          name: grpc
        volumeMounts:
{{- if .Values.clusterAgent.falco.clientTlsSecretName }}
        - name: {{ .Values.clusterAgent.falco.clientTlsSecretName }}
          mountPath: "/etc/tarian/certs/falco-integration"
{{- end }}
      volumes:
{{- if .Values.clusterAgent.falco.clientTlsSecretName }}
      - name: {{ .Values.clusterAgent.falco.clientTlsSecretName }}
        secret:
          secretName: {{ .Values.clusterAgent.falco.clientTlsSecretName }}
{{- end }}
