{{- $name := printf "%s-%s" .Release.Name "controller-manager" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    control-plane: {{ $name }}
    app: {{ .Release.Name }}
spec:
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: {{ $name }}
  type: ClusterIP