apiVersion: v1
kind: Pod
metadata:
  annotations:
    pod-agent.k8s.tarian.dev/register: "processes"
    pod-agent.k8s.tarian.dev/file-validation-interval: "7s"
  labels:
    run: nginx2
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-html
    configMap:
      name: nginx-html

