apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.server.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: tarian-server
        image: "{{ .Values.server.image.name }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
        args:
        - "--log-encoding={{ .Values.server.log.encoding }}"
        - "--log-level={{ .Values.server.log.level }}"
        - run
{{- if .Values.server.alert.alertManagerAddress }}
        - "--alertmanager-address={{ .Values.server.alert.alertManagerAddress }}"
{{- end }}
{{- if .Values.server.alert.evaluationInterval }}
        - "--alert-evaluation-interval={{ .Values.server.alert.evaluationInterval }}"
{{- end }}
{{- if .Values.server.tlsSecretName }}
        - "--tls-cert-file=/etc/tarian/tls/tls.crt"
        - "--tls-private-key-file=/etc/tarian/tls/tls.key"
{{- end }}
        ports:
        - containerPort: 50051
          name: grpc
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.server.postgresql.host | quote }}
        - name: POSTGRES_PORT
          value: {{ .Values.server.postgresql.port | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.server.postgresql.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.server.postgresql.password | quote }}
        - name: POSTGRES_DBNAME
          value: {{ .Values.server.postgresql.dbname | quote }}
        - name: POSTGRES_SSLMODE
          value: {{ .Values.server.postgresql.sslmode | quote }}
        volumeMounts:
{{- if .Values.server.tlsSecretName }}
        - name: tls
          readOnly: true
          mountPath: "/etc/tarian/tls"
{{- end }}
      volumes:
{{- if .Values.server.tlsSecretName }}
      - name: tls
        secret:
          secretName: {{ .Values.server.tlsSecretName }}
{{- end }}