name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        ports:
         - 5432:5432
        env:
          POSTGRES_PASSWORD: tarian
          POSTGRES_DB: tarian
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      # setup
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.6'

      # prepare
      - run: GO111MODULE=off go get -u github.com/mgechev/revive
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
      - run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
      - run: make protoc

      - run: make build
      - run: make lint
      - run: make unit-test
      - run: make e2e-test

  k8s-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.6'
      - uses: helm/kind-action@v1.2.0
        name: Create k8s cluster
        with:
          config: 'dev/cluster-config.yaml'

      # prepare for build
      - run: sudo apt update && sudo apt install -y jq
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
      - run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
      - run: make protoc

      # build images
      - run: bash ./dev/run-kind-registry.sh
      - run: make local-images

      # deploy to k8s
      - run: make deploy

      # wait for deployment rollout
      - run: kubectl rollout status statefulset/tarian-postgresql -n tarian-system --timeout=5m
      - run: sleep 10s
      - run: kubectl rollout status deployment/tarian-controller-manager -n tarian-system --timeout=5m
      - run: kubectl rollout status deployment/tarian-cluster-agent -n tarian-system --timeout=5m
      - run: kubectl rollout status deployment/tarian-server -n tarian-system --timeout=5m

      # run db migration and seed data
      - run: kubectl exec -ti deploy/tarian-server -n tarian-system -- ./tarian-server db migrate
      - run: kubectl exec -ti deploy/tarian-server -n tarian-system -- ./tarian-server dev seed-data
      - run: ./bin/tarianctl --server-address=localhost:31051 add constraint --name nginx --namespace default --match-labels run=nginx --allowed-processes=pause,tarian-pod-agent,nginx 
      - run: ./bin/tarianctl --server-address=localhost:31051 add constraint --name nginx --namespace default --match-labels run=nginx --allowed-file-sha256sums=/usr/share/nginx/html/index.html=38ffd4972ae513a0c79a8be4573403edcd709f0f572105362b08ff50cf6de521
      - run: ./bin/tarianctl --server-address=localhost:31051 get constraints
      - run: kubectl get pods -n tarian-system
      - run: kubectl logs deploy/tarian-controller-manager -n tarian-system
      - run: sleep 10s
      - run: kubectl get MutatingWebhookConfiguration -o yaml

      # test pod-agent injection
      - run: kubectl apply -f dev/config/monitored-pod -R
      - run: kubectl get pods

      - run: kubectl wait --for=condition=ready pod/nginx
      - run: test $(kubectl get pod nginx -o json | jq -r '.spec.containers | length') -eq 2 || (echo "expected container count 2" && false)
      - run: kubectl exec -ti nginx -c nginx -- sleep 15
      # output for debugging
      - run: ./bin/tarianctl --server-address=localhost:31051 get events
      # assert contains sleep
      - run: ./bin/tarianctl --server-address=localhost:31051 get events | grep sleep

      # output for debugging
      - run: kubectl run -ti --restart=Never get-alerts --image=curlimages/curl -- http://tarian-alertmanager.tarian-system.svc:9093/api/v2/alerts
      # assert alerts were sent
      - run: test $(kubectl run -ti --restart=Never verify-alerts --image=curlimages/curl -- http://tarian-alertmanager.tarian-system.svc:9093/api/v2/alerts | jq '. | length') -gt 1 || (echo "expected alerts created" && false)


